name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Adapt to your application's version

      - name: Install Dependencies
        run: npm install

      - name: Run OWASP Dependency-Check
        run: |
          wget https://github.com/DependencyCheck/dependency-check-bin/releases/download/v7.3.1/dependency-check.sh
          chmod +x dependency-check.sh
          ./dependency-check.sh --project "Your_Project_Name" --scan ./ --out ./

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Store your SonarQube token in GitHub secrets
        run: sonar-scanner

      - name: SourceClear
        run: |
          # Run SourceClear (now part of Synopsys) scan if available. 
          # Depending on the implementation, put the relevant commands here.

      - name: Retire.js
        run: npx retire

      - name: Checkmarx
        run: |
          # Run Checkmarx if you have integration set; add the relevant command here.

      - name: Snyk Test
        run: |
          npm install -g snyk
          snyk test
