name: DevSecOps Tests

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Update and install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            software-properties-common \
              unzip \
              curl \
              mysql-server \
              php7.4 \
              php7.4-cli \
              php7.4-fpm \
              php7.4-mysql \
              php7.4-curl \
              php7.4-mbstring \
              php7.4-xml \
              php7.4-zip \
              composer

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Setup database for Akaunting
        run: |
          mysql -u root -e "CREATE DATABASE akaunting;"
          mysql -u root -e "CREATE USER 'saad'@'localhost' IDENTIFIED BY 'Saad@9090';"
          mysql -u root -e "GRANT ALL PRIVILEGES ON akaunting.* TO 'saad'@'localhost';"
          mysql -u root -e "FLUSH PRIVILEGES;"

      - name: Install PHP dependencies using Composer
        run: composer install

      - name: Run Akaunting installation script
        run: |
          php artisan install \
              --db-name="akaunting" \
              --db-username="akaunting_user" \
              --db-password="password" \
              --admin-email="saad.16ouafir@gmail.com" \
              --admin-password="saad9090"
      - name: install Composer dependencies
        run: composer install

      - name: install front dependencies
        run: npm install

      - name: build project
        run: npm run dev

      - name: run project
        run: php -S 127.0.0.1:8000

      # OWASP Dependency-Check (Alternative)
      - name: OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.4.1/dependency-check-7.4.1-release.zip
          unzip dependency-check-7.4.1-release.zip
          java -jar dependency-check-7.4.1-release/bin/dependency-check.sh --project Akaunting --scan . --format ALL --out ./dependency-check-report

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        with:
          args: -Dsonar.projectKey=saad-ouafir_DEVSECOPS-AKAUNTING

      - name: SourceClear Scan
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | bash

      # Retire.js Scan (Alternative)
      - name: Retire.js Scan
        run: |
          npm install -g retire
          retire --outputformat json --outputpath retirejs-report.json

      - name: Snyk Scan
        uses: snyk/actions@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
