name: DevSecOps Tests

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Install dependencies
        run: composer install

      - name: OWASP Dependency-Check
        uses: jeremylong/gh-dependency-check@v4.0.0
        with:
          project: "Akaunting"
          format: "ALL"
          output-directory: "./dependency-check-report"

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .

      - name: SourceClear Scan
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | bash

      - name: Retire.js Scan
        uses: nicojs/retire-action@v2.0.0

      - name: Snyk Scan
        uses: snyk/actions@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
