name: DevSecOps Tests

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Install dependencies
        run: composer install

      # OWASP Dependency-Check (Alternative)
      - name: OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.4.1/dependency-check-7.4.1-release.zip
          unzip dependency-check-7.4.1-release.zip
          java -jar dependency-check-7.4.1-release/bin/dependency-check.sh --project Akaunting --scan . --format ALL --out ./dependency-check-report

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        with:
          args: -Dsonar.projectKey=saad-ouafir_DEVSECOPS-AKAUNTING

      - name: SourceClear Scan
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | bash

      # Retire.js Scan (Alternative)
      - name: Retire.js Scan
        run: |
          npm install -g retire
          retire --outputformat json --outputpath retirejs-report.json

      - name: Snyk Scan
        uses: snyk/actions@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
